# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Zdjęcia Krzysia"
subtitle: "Fotografia jest moją pasją"
author:  "Krzyś"
header:
 title: "Zdjęcia Krzysia"
 subtitle: "Kliknij w zdjęcie, aby powiększyć"
footer:
 name: "Cześć, Jestem Krzyś "
 bio: "Od zawsze lubiłem robić zdjęcia, teraz możecie je zobaczyć."
social_urls:
  instagram: "https://www.instagram.com/zdjeciakrzysia"
  mail: "mailto:kontaktdokrzysia@gmail.com"
